[tool.poetry]
name = "liga-scraper"
version = "0.1.0"
description = "Web scraper for liga statistics"

[tool.poetry.dependencies]
python = "^3.9"
selenium = "^4.18.1"
pandas = "^2.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
